export default {
  documentTitle: 'Auto Expo · منصة معارض السيارات العالمية', brand: 'Auto Expo',
  nav: { map: 'الخريطة العالمية', overview: 'المعارض المميزة', procurement: 'مسار المشتريات', sales: 'مسار المبيعات', monthly: 'شهرياً', category: 'الفئات', country: 'حسب الدولة', preview: 'معاينة 2027', starred: 'موصى بها' },
  common: { all: 'الكل', search: 'البحث عن المعارض…', clearFilters: 'مسح عوامل التصفية', comingSoon: 'قريباً', officialWebsite: 'الموقع الرسمي', officialInfo: 'المعلومات الرسمية', date: 'التاريخ', location: 'الموقع', category: 'الفئة', focus: 'الموضوع', audience: 'الجمهور', country: 'الدولة', region: 'المنطقة', relatedExhibitions: 'المعارض ذات الصلة', noResults: 'لا يوجد معرض يطابق عوامل التصفية الحالية.', unavailable: 'يجري التحقق من المحتوى العربي.', back: 'رجوع', zoomIn: 'تكبير الخريطة', zoomOut: 'تصغير الخريطة', resetMap: 'إعادة ضبط الخريطة', theme: 'تبديل المظهر' },
  overview: { featured: 'المعارض المميزة', upcoming: 'هذا الشهر والشهر المقبل', exhibitions: 'معارض 2026', categories: 'فئات المعارض', coverage: 'الدول والمناطق المشمولة', thisMonth: 'هذا الشهر' },
  map: { title: 'المعارض العالمية هذا الشهر', distribution: 'التوزيع العالمي للمعارض', noEvents: 'لا توجد معارض في هذه المنطقة للشهر المحدد.', loadError: 'تعذر تحميل النتائج.', schedule: 'الجدول', preview: 'معاينة', events: 'معارض', allEvents: 'جميع المعارض', clearSelection: 'مسح التحديد' },
  procurement: { title: 'مسار المشتريات', intro: 'ابدأ بهندسة المركبة، ثم حدّد الموردين ومسارات التقنية والمعارض المناسبة لكل مجموعة.', whyMatch: 'لماذا هذا التطابق؟', obtain: 'ما الذي تحصل عليه في الموقع', doNotAttend: 'متى لا تشارك', alternative: 'الإجراء البديل', preliminary: 'تطابق أولي مبني على المعلومات المتاحة.', noMatches: 'لم يتم العثور على تطابق مع المعلومات المقدمة.', tasks: { supplier: 'مورد جديد / مصدر ثانٍ', technology: 'اختيار التقنية ومقارنة الحلول', cost: 'خفض التكلفة واستبدال المواد والتوطين', qualification: 'تقييم جودة المورد والشهادات والقدرة', aftermarket: 'خدمات ما بعد البيع وإعادة التصنيع واللوجستيات العكسية' } },
  sales: { title: 'مسار المبيعات', directCustomers: 'العملاء المباشرون', technicalSpecifiers: 'محددو المواصفات الفنية', salesModel: 'نموذج المبيعات', partners: 'الشركاء', viewProcurement: 'عرض احتياجات المشتريات' },
  search: { placeholder: 'البحث باسم المعرض أو الموقع أو الفئة…', empty: 'لا يوجد معرض يطابق البحث.' }
};
