export default {
  documentTitle: 'Auto Expo · Plateforme mondiale des salons automobiles', brand: 'Auto Expo',
  nav: { map: 'Carte mondiale', overview: 'Expositions à la une', procurement: 'Parcours d’achat', sales: 'Parcours commercial', monthly: 'Mensuel', category: 'Catégories', country: 'Par pays', preview: 'Aperçu 2027', starred: 'Recommandées' },
  common: { all: 'Toutes', search: 'Rechercher des expositions...', clearFilters: 'Effacer les filtres', comingSoon: 'Bientôt disponible', officialWebsite: 'Site officiel', officialInfo: 'Informations officielles', date: 'Date', location: 'Lieu', category: 'Catégorie', focus: 'Thème', audience: 'Public', country: 'Pays', region: 'Région', relatedExhibitions: 'Expositions associées', noResults: 'Aucune exposition ne correspond aux filtres actuels.', unavailable: 'Le contenu en français est en cours de vérification.', back: 'Retour', zoomIn: 'Agrandir la carte', zoomOut: 'Réduire la carte', resetMap: 'Réinitialiser la carte', theme: 'Changer de thème' },
  overview: { featured: 'Expositions à la une', upcoming: 'Ce mois-ci et le mois prochain', exhibitions: 'Expositions 2026', categories: 'Catégories d’expositions', coverage: 'Pays et régions couverts', thisMonth: 'Ce mois-ci' },
  map: { title: 'Expositions mondiales ce mois-ci', distribution: 'Répartition mondiale des expositions', noEvents: 'Aucune exposition dans cette zone pour le mois sélectionné.', loadError: 'Impossible de charger les résultats.', schedule: 'Programme', preview: 'Aperçu', events: 'expositions', allEvents: 'Toutes les expositions', clearSelection: 'Effacer la sélection' },
  procurement: { title: 'Parcours d’achat', intro: 'Commencez par l’architecture du véhicule, puis identifiez les fournisseurs, les technologies et les expositions pertinentes par ensemble.', whyMatch: 'Pourquoi cette correspondance ?', obtain: 'À obtenir sur place', doNotAttend: 'Quand ne pas participer', alternative: 'Action alternative', preliminary: 'Correspondance préliminaire fondée sur les informations disponibles.', noMatches: 'Aucune correspondance trouvée avec les informations fournies.', tasks: { supplier: 'Nouveau fournisseur / seconde source', technology: 'Choix technologique et comparaison des solutions', cost: 'Réduction des coûts, substitution des matériaux et localisation', qualification: 'Évaluation de la qualité, de la certification et de la capacité fournisseur', aftermarket: 'Après-vente, remanufacturation et chaîne logistique inverse' } },
  sales: { title: 'Parcours commercial', directCustomers: 'Clients directs', technicalSpecifiers: 'Prescripteurs techniques', salesModel: 'Modèle commercial', partners: 'Partenaires', viewProcurement: 'Voir les besoins d’achat' },
  search: { placeholder: 'Rechercher par nom, lieu ou catégorie...', empty: 'Aucune exposition ne correspond à votre recherche.' }
};
