export default {
  documentTitle: 'Auto Expo · वैश्विक ऑटोमोटिव प्रदर्शनी मंच', brand: 'Auto Expo',
  nav: { map: 'विश्व मानचित्र', overview: 'प्रमुख प्रदर्शनियाँ', procurement: 'खरीद मार्ग', sales: 'बिक्री मार्ग', monthly: 'मासिक', category: 'श्रेणियाँ', country: 'देश के अनुसार', preview: '2027 पूर्वावलोकन', starred: 'अनुशंसित' },
  common: { all: 'सभी', search: 'प्रदर्शनियाँ खोजें…', clearFilters: 'फ़िल्टर साफ़ करें', comingSoon: 'जल्द आ रहा है', officialWebsite: 'आधिकारिक वेबसाइट', officialInfo: 'आधिकारिक जानकारी', date: 'तारीख', location: 'स्थान', category: 'श्रेणी', focus: 'फोकस', audience: 'दर्शक', country: 'देश', region: 'क्षेत्र', relatedExhibitions: 'संबंधित प्रदर्शनियाँ', noResults: 'वर्तमान फ़िल्टर से कोई प्रदर्शनी मेल नहीं खाती।', unavailable: 'हिन्दी सामग्री की जाँच की जा रही है।', back: 'वापस', zoomIn: 'मानचित्र बड़ा करें', zoomOut: 'मानचित्र छोटा करें', resetMap: 'मानचित्र रीसेट करें', theme: 'थीम बदलें' },
  overview: { featured: 'प्रमुख प्रदर्शनियाँ', upcoming: 'इस महीने और अगले महीने', exhibitions: '2026 प्रदर्शनियाँ', categories: 'प्रदर्शनी श्रेणियाँ', coverage: 'शामिल देश और क्षेत्र', thisMonth: 'इस महीने' },
  map: { title: 'इस महीने की वैश्विक प्रदर्शनियाँ', distribution: 'वैश्विक प्रदर्शनी वितरण', noEvents: 'चयनित महीने में इस क्षेत्र में कोई प्रदर्शनी नहीं है।', loadError: 'परिणाम लोड नहीं हो सके।', schedule: 'कार्यक्रम', preview: 'पूर्वावलोकन', events: 'प्रदर्शनियाँ', allEvents: 'सभी प्रदर्शनियाँ', clearSelection: 'चयन साफ़ करें' },
  procurement: { title: 'खरीद मार्ग', intro: 'वाहन आर्किटेक्चर से शुरू करें और प्रत्येक असेंबली के लिए आपूर्तिकर्ता, तकनीकी मार्ग और प्रासंगिक प्रदर्शनियाँ पहचानें।', whyMatch: 'यह मिलान क्यों?', obtain: 'स्थल पर क्या प्राप्त करें', doNotAttend: 'कब भाग न लें', alternative: 'वैकल्पिक कार्रवाई', preliminary: 'उपलब्ध जानकारी पर आधारित प्रारंभिक मिलान।', noMatches: 'दी गई जानकारी से कोई मिलान नहीं मिला।', tasks: { supplier: 'नया आपूर्तिकर्ता / दूसरा स्रोत', technology: 'तकनीक चयन और समाधान तुलना', cost: 'लागत कमी, सामग्री प्रतिस्थापन और स्थानीयकरण', qualification: 'आपूर्तिकर्ता गुणवत्ता, प्रमाणन और क्षमता मूल्यांकन', aftermarket: 'आफ्टरमार्केट, रीमैन्युफैक्चरिंग और रिवर्स लॉजिस्टिक्स' } },
  sales: { title: 'बिक्री मार्ग', directCustomers: 'प्रत्यक्ष ग्राहक', technicalSpecifiers: 'तकनीकी विनिर्देशक', salesModel: 'बिक्री मॉडल', partners: 'भागीदार', viewProcurement: 'खरीद आवश्यकताएँ देखें' },
  search: { placeholder: 'प्रदर्शनी नाम, स्थान या श्रेणी से खोजें…', empty: 'खोज से कोई प्रदर्शनी मेल नहीं खाती।' }
};
