export default {
  documentTitle: 'Auto Expo · Hub Pameran Otomotif Global', brand: 'Auto Expo',
  nav: { map: 'Peta dunia', overview: 'Pameran unggulan', procurement: 'Jalur pengadaan', sales: 'Jalur penjualan', monthly: 'Bulanan', category: 'Kategori', country: 'Menurut negara', preview: 'Pratinjau 2027', starred: 'Rekomendasi' },
  common: { all: 'Semua', search: 'Cari pameran…', clearFilters: 'Hapus filter', comingSoon: 'Segera hadir', officialWebsite: 'Situs resmi', officialInfo: 'Informasi resmi', date: 'Tanggal', location: 'Lokasi', category: 'Kategori', focus: 'Fokus', audience: 'Audiens', country: 'Negara', region: 'Wilayah', relatedExhibitions: 'Pameran terkait', noResults: 'Tidak ada pameran yang cocok dengan filter saat ini.', unavailable: 'Konten bahasa Indonesia sedang diverifikasi.', back: 'Kembali', zoomIn: 'Perbesar peta', zoomOut: 'Perkecil peta', resetMap: 'Atur ulang peta', theme: 'Ganti tema' },
  overview: { featured: 'Pameran unggulan', upcoming: 'Bulan ini dan bulan depan', exhibitions: 'Pameran 2026', categories: 'Kategori pameran', coverage: 'Negara dan wilayah yang tercakup', thisMonth: 'Bulan ini' },
  map: { title: 'Pameran global bulan ini', distribution: 'Distribusi pameran global', noEvents: 'Tidak ada pameran di wilayah ini pada bulan yang dipilih.', loadError: 'Hasil tidak dapat dimuat.', schedule: 'Jadwal', preview: 'Pratinjau', events: 'pameran', allEvents: 'Semua pameran', clearSelection: 'Hapus pilihan' },
  procurement: { title: 'Jalur pengadaan', intro: 'Mulai dari arsitektur kendaraan, lalu identifikasi pemasok, jalur teknologi, dan pameran yang relevan untuk setiap rakitan.', whyMatch: 'Mengapa cocok?', obtain: 'Yang perlu diperoleh di lokasi', doNotAttend: 'Kapan tidak perlu hadir', alternative: 'Tindakan alternatif', preliminary: 'Pencocokan awal berdasarkan informasi yang tersedia.', noMatches: 'Tidak ditemukan kecocokan berdasarkan informasi yang diberikan.', tasks: { supplier: 'Pemasok baru / sumber kedua', technology: 'Pemilihan teknologi dan perbandingan solusi', cost: 'Pengurangan biaya, substitusi material, dan lokalisasi', qualification: 'Penilaian kualitas, sertifikasi, dan kapasitas pemasok', aftermarket: 'Aftermarket, remanufaktur, dan logistik balik' } },
  sales: { title: 'Jalur penjualan', directCustomers: 'Pelanggan langsung', technicalSpecifiers: 'Penentu spesifikasi teknis', salesModel: 'Model penjualan', partners: 'Mitra', viewProcurement: 'Lihat kebutuhan pengadaan' },
  search: { placeholder: 'Cari berdasarkan nama pameran, lokasi, atau kategori…', empty: 'Tidak ada pameran yang cocok dengan pencarian.' }
};
