export default {
  documentTitle: 'Auto Expo · Hub globale delle fiere automobilistiche', brand: 'Auto Expo',
  nav: { map: 'Mappa globale', overview: 'Fiere in evidenza', procurement: 'Percorso acquisti', sales: 'Percorso vendite', monthly: 'Mensile', category: 'Categorie', country: 'Per paese', preview: 'Anteprima 2027', starred: 'Consigliate' },
  common: { all: 'Tutte', search: 'Cerca fiere…', clearFilters: 'Cancella filtri', comingSoon: 'Presto disponibile', officialWebsite: 'Sito ufficiale', officialInfo: 'Informazioni ufficiali', date: 'Data', location: 'Luogo', category: 'Categoria', focus: 'Focus', audience: 'Pubblico', country: 'Paese', region: 'Regione', relatedExhibitions: 'Fiere correlate', noResults: 'Nessuna fiera corrisponde ai filtri attuali.', unavailable: 'I contenuti in italiano sono in fase di verifica.', back: 'Indietro', zoomIn: 'Ingrandisci mappa', zoomOut: 'Riduci mappa', resetMap: 'Reimposta mappa', theme: 'Cambia tema' },
  overview: { featured: 'Fiere in evidenza', upcoming: 'Questo mese e il prossimo', exhibitions: 'Fiere 2026', categories: 'Categorie di fiere', coverage: 'Paesi e regioni coperte', thisMonth: 'Questo mese' },
  map: { title: 'Fiere globali di questo mese', distribution: 'Distribuzione globale delle fiere', noEvents: 'Nessuna fiera in questa zona per il mese selezionato.', loadError: 'Impossibile caricare i risultati.', schedule: 'Calendario', preview: 'Anteprima', events: 'fiere', allEvents: 'Tutte le fiere', clearSelection: 'Cancella selezione' },
  procurement: { title: 'Percorso acquisti', intro: 'Parti dall’architettura del veicolo, poi identifica fornitori, percorsi tecnologici e fiere rilevanti per ogni gruppo.', whyMatch: 'Perché questa corrispondenza?', obtain: 'Cosa ottenere sul posto', doNotAttend: 'Quando non partecipare', alternative: 'Azione alternativa', preliminary: 'Corrispondenza preliminare basata sulle informazioni disponibili.', noMatches: 'Nessuna corrispondenza trovata in base alle informazioni fornite.', tasks: { supplier: 'Nuovo fornitore / seconda fonte', technology: 'Scelta tecnologica e confronto delle soluzioni', cost: 'Riduzione dei costi, sostituzione dei materiali e localizzazione', qualification: 'Valutazione di qualità, certificazione e capacità del fornitore', aftermarket: 'Aftermarket, remanufacturing e logistica inversa' } },
  sales: { title: 'Percorso vendite', directCustomers: 'Clienti diretti', technicalSpecifiers: 'Responsabili delle specifiche tecniche', salesModel: 'Modello di vendita', partners: 'Partner', viewProcurement: 'Vedi le esigenze di acquisto' },
  search: { placeholder: 'Cerca per nome della fiera, luogo o categoria…', empty: 'Nessuna fiera corrisponde alla ricerca.' }
};
