export default {
  documentTitle: 'Auto Expo · Küresel Otomotiv Fuarları Platformu', brand: 'Auto Expo',
  nav: { map: 'Dünya haritası', overview: 'Öne çıkan fuarlar', procurement: 'Satın alma yolu', sales: 'Satış yolu', monthly: 'Aylık', category: 'Kategoriler', country: 'Ülkeye göre', preview: '2027 önizlemesi', starred: 'Önerilen' },
  common: { all: 'Tümü', search: 'Fuar ara…', clearFilters: 'Filtreleri temizle', comingSoon: 'Yakında', officialWebsite: 'Resmî web sitesi', officialInfo: 'Resmî bilgiler', date: 'Tarih', location: 'Konum', category: 'Kategori', focus: 'Odak', audience: 'Hedef kitle', country: 'Ülke', region: 'Bölge', relatedExhibitions: 'İlgili fuarlar', noResults: 'Mevcut filtrelerle eşleşen fuar yok.', unavailable: 'Türkçe içerik doğrulanıyor.', back: 'Geri', zoomIn: 'Haritayı büyüt', zoomOut: 'Haritayı küçült', resetMap: 'Haritayı sıfırla', theme: 'Temayı değiştir' },
  overview: { featured: 'Öne çıkan fuarlar', upcoming: 'Bu ay ve gelecek ay', exhibitions: '2026 fuarları', categories: 'Fuar kategorileri', coverage: 'Kapsanan ülkeler ve bölgeler', thisMonth: 'Bu ay' },
  map: { title: 'Bu ayın küresel fuarları', distribution: 'Küresel fuar dağılımı', noEvents: 'Seçilen ayda bu bölgede fuar yok.', loadError: 'Sonuçlar yüklenemedi.', schedule: 'Program', preview: 'Önizleme', events: 'fuar', allEvents: 'Tüm fuarlar', clearSelection: 'Seçimi temizle' },
  procurement: { title: 'Satın alma yolu', intro: 'Araç mimarisiyle başlayın; her montaj için tedarikçileri, teknoloji rotalarını ve ilgili fuarları belirleyin.', whyMatch: 'Bu eşleşme neden uygun?', obtain: 'Etkinlikte elde edilecekler', doNotAttend: 'Ne zaman katılmamalı', alternative: 'Alternatif işlem', preliminary: 'Mevcut bilgilere dayalı ön eşleşme.', noMatches: 'Verilen bilgilere göre eşleşme bulunamadı.', tasks: { supplier: 'Yeni tedarikçi / ikinci kaynak', technology: 'Teknoloji seçimi ve çözüm karşılaştırması', cost: 'Maliyet azaltma, malzeme ikamesi ve yerlileştirme', qualification: 'Tedarikçi kalite, sertifikasyon ve kapasite değerlendirmesi', aftermarket: 'Aftermarket, remanüfaktür ve tersine lojistik' } },
  sales: { title: 'Satış yolu', directCustomers: 'Doğrudan müşteriler', technicalSpecifiers: 'Teknik şartname belirleyicileri', salesModel: 'Satış modeli', partners: 'Ortaklar', viewProcurement: 'Satın alma ihtiyaçlarını görüntüle' },
  search: { placeholder: 'Fuar adı, konum veya kategoriyle ara…', empty: 'Aramanızla eşleşen fuar yok.' }
};
